import type { Metadata } from "next";

import "./global.scss";
import { GoogleAnalytics, GoogleTagManager } from "@next/third-parties/google";
import { MusicPlayer } from "@_components/molecules";
import { envConfig } from "@_utils/config";
import Framer from "./Framer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Framer>{children}</Framer>
        <MusicPlayer src={`${envConfig.assetPath}/home_bgm.mp3`} />
      </body>
      <GoogleAnalytics gaId={envConfig.GA_ID!} />
      <GoogleTagManager gtmId={envConfig.GTM_ID!} />
    </html>
  );
}
